"""
SaleFlex.PyPOS - Database Initial Data

Copyright (c) 2025 Ferhat Mousavi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

from data_layer.model import Country



from core.logger import get_logger

logger = get_logger(__name__)

def _insert_countries(session):
    """Insert countries if not exists"""
    country_exists = session.query(Country).first()
    if not country_exists:
        countries = [
            {"name": "Afghanistan", "code": "AF", "short_name": "AFG", "numeric_code": 4},
            {"name": "Albania", "code": "AL", "short_name": "ALB", "numeric_code": 8},
            {"name": "Algeria", "code": "DZ", "short_name": "DZA", "numeric_code": 12},
            {"name": "Andorra", "code": "AD", "short_name": "AND", "numeric_code": 20},
            {"name": "Angola", "code": "AO", "short_name": "AGO", "numeric_code": 24},
            {"name": "Argentina", "code": "AR", "short_name": "ARG", "numeric_code": 32},
            {"name": "Armenia", "code": "AM", "short_name": "ARM", "numeric_code": 51},
            {"name": "Australia", "code": "AU", "short_name": "AUS", "numeric_code": 36},
            {"name": "Austria", "code": "AT", "short_name": "AUT", "numeric_code": 40},
            {"name": "Azerbaijan", "code": "AZ", "short_name": "AZE", "numeric_code": 31},
            {"name": "Bahamas", "code": "BS", "short_name": "BHS", "numeric_code": 44},
            {"name": "Bahrain", "code": "BH", "short_name": "BHR", "numeric_code": 48},
            {"name": "Bangladesh", "code": "BD", "short_name": "BGD", "numeric_code": 50},
            {"name": "Barbados", "code": "BB", "short_name": "BRB", "numeric_code": 52},
            {"name": "Belarus", "code": "BY", "short_name": "BLR", "numeric_code": 112},
            {"name": "Belgium", "code": "BE", "short_name": "BEL", "numeric_code": 56},
            {"name": "Belize", "code": "BZ", "short_name": "BLZ", "numeric_code": 84},
            {"name": "Benin", "code": "BJ", "short_name": "BEN", "numeric_code": 204},
            {"name": "Bhutan", "code": "BT", "short_name": "BTN", "numeric_code": 64},
            {"name": "Bolivia", "code": "BO", "short_name": "BOL", "numeric_code": 68},
            {"name": "Bosnia and Herzegovina", "code": "BA", "short_name": "BIH", "numeric_code": 70},
            {"name": "Botswana", "code": "BW", "short_name": "BWA", "numeric_code": 72},
            {"name": "Brazil", "code": "BR", "short_name": "BRA", "numeric_code": 76},
            {"name": "Brunei", "code": "BN", "short_name": "BRN", "numeric_code": 96},
            {"name": "Bulgaria", "code": "BG", "short_name": "BGR", "numeric_code": 100},
            {"name": "Burkina Faso", "code": "BF", "short_name": "BFA", "numeric_code": 854},
            {"name": "Burundi", "code": "BI", "short_name": "BDI", "numeric_code": 108},
            {"name": "Cabo Verde", "code": "CV", "short_name": "CPV", "numeric_code": 132},
            {"name": "Cambodia", "code": "KH", "short_name": "KHM", "numeric_code": 116},
            {"name": "Cameroon", "code": "CM", "short_name": "CMR", "numeric_code": 120},
            {"name": "Canada", "code": "CA", "short_name": "CAN", "numeric_code": 124},
            {"name": "Central African Republic", "code": "CF", "short_name": "CAF", "numeric_code": 140},
            {"name": "Chad", "code": "TD", "short_name": "TCD", "numeric_code": 148},
            {"name": "Chile", "code": "CL", "short_name": "CHL", "numeric_code": 152},
            {"name": "China", "code": "CN", "short_name": "CHN", "numeric_code": 156},
            {"name": "Colombia", "code": "CO", "short_name": "COL", "numeric_code": 170},
            {"name": "Comoros", "code": "KM", "short_name": "COM", "numeric_code": 174},
            {"name": "Congo, Democratic Republic of the", "code": "CD", "short_name": "COD", "numeric_code": 180},
            {"name": "Congo, Republic of the", "code": "CG", "short_name": "COG", "numeric_code": 178},
            {"name": "Costa Rica", "code": "CR", "short_name": "CRI", "numeric_code": 188},
            {"name": "Croatia", "code": "HR", "short_name": "HRV", "numeric_code": 191},
            {"name": "Cuba", "code": "CU", "short_name": "CUB", "numeric_code": 192},
            {"name": "Cyprus", "code": "CY", "short_name": "CYP", "numeric_code": 196},
            {"name": "Czech Republic", "code": "CZ", "short_name": "CZE", "numeric_code": 203},
            {"name": "Denmark", "code": "DK", "short_name": "DNK", "numeric_code": 208},
            {"name": "Djibouti", "code": "DJ", "short_name": "DJI", "numeric_code": 262},
            {"name": "Dominica", "code": "DM", "short_name": "DMA", "numeric_code": 212},
            {"name": "Dominican Republic", "code": "DO", "short_name": "DOM", "numeric_code": 214},
            {"name": "Ecuador", "code": "EC", "short_name": "ECU", "numeric_code": 218},
            {"name": "Egypt", "code": "EG", "short_name": "EGY", "numeric_code": 818},
            {"name": "El Salvador", "code": "SV", "short_name": "SLV", "numeric_code": 222},
            {"name": "Equatorial Guinea", "code": "GQ", "short_name": "GNQ", "numeric_code": 226},
            {"name": "Eritrea", "code": "ER", "short_name": "ERI", "numeric_code": 232},
            {"name": "Estonia", "code": "EE", "short_name": "EST", "numeric_code": 233},
            {"name": "Eswatini", "code": "SZ", "short_name": "SWZ", "numeric_code": 748},
            {"name": "Ethiopia", "code": "ET", "short_name": "ETH", "numeric_code": 231},
            {"name": "Fiji", "code": "FJ", "short_name": "FJI", "numeric_code": 242},
            {"name": "Finland", "code": "FI", "short_name": "FIN", "numeric_code": 246},
            {"name": "France", "code": "FR", "short_name": "FRA", "numeric_code": 250},
            {"name": "Gabon", "code": "GA", "short_name": "GAB", "numeric_code": 266},
            {"name": "Gambia", "code": "GM", "short_name": "GMB", "numeric_code": 270},
            {"name": "Georgia", "code": "GE", "short_name": "GEO", "numeric_code": 268},
            {"name": "Germany", "code": "DE", "short_name": "DEU", "numeric_code": 276},
            {"name": "Ghana", "code": "GH", "short_name": "GHA", "numeric_code": 288},
            {"name": "Greece", "code": "GR", "short_name": "GRC", "numeric_code": 300},
            {"name": "Grenada", "code": "GD", "short_name": "GRD", "numeric_code": 308},
            {"name": "Guatemala", "code": "GT", "short_name": "GTM", "numeric_code": 320},
            {"name": "Guinea", "code": "GN", "short_name": "GIN", "numeric_code": 324},
            {"name": "Guinea-Bissau", "code": "GW", "short_name": "GNB", "numeric_code": 624},
            {"name": "Guyana", "code": "GY", "short_name": "GUY", "numeric_code": 328},
            {"name": "Haiti", "code": "HT", "short_name": "HTI", "numeric_code": 332},
            {"name": "Honduras", "code": "HN", "short_name": "HND", "numeric_code": 340},
            {"name": "Hungary", "code": "HU", "short_name": "HUN", "numeric_code": 348},
            {"name": "Iceland", "code": "IS", "short_name": "ISL", "numeric_code": 352},
            {"name": "India", "code": "IN", "short_name": "IND", "numeric_code": 356},
            {"name": "Indonesia", "code": "ID", "short_name": "IDN", "numeric_code": 360},
            {"name": "Iran", "code": "IR", "short_name": "IRN", "numeric_code": 364},
            {"name": "Iraq", "code": "IQ", "short_name": "IRQ", "numeric_code": 368},
            {"name": "Ireland", "code": "IE", "short_name": "IRL", "numeric_code": 372},
            {"name": "Israel", "code": "IL", "short_name": "ISR", "numeric_code": 376},
            {"name": "Italy", "code": "IT", "short_name": "ITA", "numeric_code": 380},
            {"name": "Jamaica", "code": "JM", "short_name": "JAM", "numeric_code": 388},
            {"name": "Japan", "code": "JP", "short_name": "JPN", "numeric_code": 392},
            {"name": "Jordan", "code": "JO", "short_name": "JOR", "numeric_code": 400},
            {"name": "Kazakhstan", "code": "KZ", "short_name": "KAZ", "numeric_code": 398},
            {"name": "Kenya", "code": "KE", "short_name": "KEN", "numeric_code": 404},
            {"name": "Kiribati", "code": "KI", "short_name": "KIR", "numeric_code": 296},
            {"name": "Korea, North", "code": "KP", "short_name": "PRK", "numeric_code": 408},
            {"name": "Korea, South", "code": "KR", "short_name": "KOR", "numeric_code": 410},
            {"name": "Kuwait", "code": "KW", "short_name": "KWT", "numeric_code": 414},
            {"name": "Kyrgyzstan", "code": "KG", "short_name": "KGZ", "numeric_code": 417},
            {"name": "Laos", "code": "LA", "short_name": "LAO", "numeric_code": 418},
            {"name": "Latvia", "code": "LV", "short_name": "LVA", "numeric_code": 428},
            {"name": "Lebanon", "code": "LB", "short_name": "LBN", "numeric_code": 422},
            {"name": "Lesotho", "code": "LS", "short_name": "LSO", "numeric_code": 426},
            {"name": "Liberia", "code": "LR", "short_name": "LBR", "numeric_code": 430},
            {"name": "Libya", "code": "LY", "short_name": "LBY", "numeric_code": 434},
            {"name": "Liechtenstein", "code": "LI", "short_name": "LIE", "numeric_code": 438},
            {"name": "Lithuania", "code": "LT", "short_name": "LTU", "numeric_code": 440},
            {"name": "Luxembourg", "code": "LU", "short_name": "LUX", "numeric_code": 442},
            {"name": "Madagascar", "code": "MG", "short_name": "MDG", "numeric_code": 450},
            {"name": "Malawi", "code": "MW", "short_name": "MWI", "numeric_code": 454},
            {"name": "Malaysia", "code": "MY", "short_name": "MYS", "numeric_code": 458},
            {"name": "Maldives", "code": "MV", "short_name": "MDV", "numeric_code": 462},
            {"name": "Mali", "code": "ML", "short_name": "MLI", "numeric_code": 466},
            {"name": "Malta", "code": "MT", "short_name": "MLT", "numeric_code": 470},
            {"name": "Marshall Islands", "code": "MH", "short_name": "MHL", "numeric_code": 584},
            {"name": "Mauritania", "code": "MR", "short_name": "MRT", "numeric_code": 478},
            {"name": "Mauritius", "code": "MU", "short_name": "MUS", "numeric_code": 480},
            {"name": "Mexico", "code": "MX", "short_name": "MEX", "numeric_code": 484},
            {"name": "Micronesia", "code": "FM", "short_name": "FSM", "numeric_code": 583},
            {"name": "Moldova", "code": "MD", "short_name": "MDA", "numeric_code": 498},
            {"name": "Monaco", "code": "MC", "short_name": "MCO", "numeric_code": 492},
            {"name": "Mongolia", "code": "MN", "short_name": "MNG", "numeric_code": 496},
            {"name": "Montenegro", "code": "ME", "short_name": "MNE", "numeric_code": 499},
            {"name": "Morocco", "code": "MA", "short_name": "MAR", "numeric_code": 504},
            {"name": "Mozambique", "code": "MZ", "short_name": "MOZ", "numeric_code": 508},
            {"name": "Myanmar", "code": "MM", "short_name": "MMR", "numeric_code": 104},
            {"name": "Namibia", "code": "NA", "short_name": "NAM", "numeric_code": 516},
            {"name": "Nauru", "code": "NR", "short_name": "NRU", "numeric_code": 520},
            {"name": "Nepal", "code": "NP", "short_name": "NPL", "numeric_code": 524},
            {"name": "Netherlands", "code": "NL", "short_name": "NLD", "numeric_code": 528},
            {"name": "New Zealand", "code": "NZ", "short_name": "NZL", "numeric_code": 554},
            {"name": "Nicaragua", "code": "NI", "short_name": "NIC", "numeric_code": 558},
            {"name": "Niger", "code": "NE", "short_name": "NER", "numeric_code": 562},
            {"name": "Nigeria", "code": "NG", "short_name": "NGA", "numeric_code": 566},
            {"name": "North Macedonia", "code": "MK", "short_name": "MKD", "numeric_code": 807},
            {"name": "Norway", "code": "NO", "short_name": "NOR", "numeric_code": 578},
            {"name": "Oman", "code": "OM", "short_name": "OMN", "numeric_code": 512},
            {"name": "Pakistan", "code": "PK", "short_name": "PAK", "numeric_code": 586},
            {"name": "Palau", "code": "PW", "short_name": "PLW", "numeric_code": 585},
            {"name": "Panama", "code": "PA", "short_name": "PAN", "numeric_code": 591},
            {"name": "Papua New Guinea", "code": "PG", "short_name": "PNG", "numeric_code": 598},
            {"name": "Paraguay", "code": "PY", "short_name": "PRY", "numeric_code": 600},
            {"name": "Peru", "code": "PE", "short_name": "PER", "numeric_code": 604},
            {"name": "Philippines", "code": "PH", "short_name": "PHL", "numeric_code": 608},
            {"name": "Poland", "code": "PL", "short_name": "POL", "numeric_code": 616},
            {"name": "Portugal", "code": "PT", "short_name": "PRT", "numeric_code": 620},
            {"name": "Qatar", "code": "QA", "short_name": "QAT", "numeric_code": 634},
            {"name": "Romania", "code": "RO", "short_name": "ROU", "numeric_code": 642},
            {"name": "Russia", "code": "RU", "short_name": "RUS", "numeric_code": 643},
            {"name": "Rwanda", "code": "RW", "short_name": "RWA", "numeric_code": 646},
            {"name": "Saint Kitts and Nevis", "code": "KN", "short_name": "KNA", "numeric_code": 659},
            {"name": "Saint Lucia", "code": "LC", "short_name": "LCA", "numeric_code": 662},
            {"name": "Saint Vincent and the Grenadines", "code": "VC", "short_name": "VCT", "numeric_code": 670},
            {"name": "Samoa", "code": "WS", "short_name": "WSM", "numeric_code": 882},
            {"name": "San Marino", "code": "SM", "short_name": "SMR", "numeric_code": 674},
            {"name": "Sao Tome and Principe", "code": "ST", "short_name": "STP", "numeric_code": 678},
            {"name": "Saudi Arabia", "code": "SA", "short_name": "SAU", "numeric_code": 682},
            {"name": "Senegal", "code": "SN", "short_name": "SEN", "numeric_code": 686},
            {"name": "Serbia", "code": "RS", "short_name": "SRB", "numeric_code": 688},
            {"name": "Seychelles", "code": "SC", "short_name": "SYC", "numeric_code": 690},
            {"name": "Sierra Leone", "code": "SL", "short_name": "SLE", "numeric_code": 694},
            {"name": "Singapore", "code": "SG", "short_name": "SGP", "numeric_code": 702},
            {"name": "Slovakia", "code": "SK", "short_name": "SVK", "numeric_code": 703},
            {"name": "Slovenia", "code": "SI", "short_name": "SVN", "numeric_code": 705},
            {"name": "Solomon Islands", "code": "SB", "short_name": "SLB", "numeric_code": 90},
            {"name": "Somalia", "code": "SO", "short_name": "SOM", "numeric_code": 706},
            {"name": "South Africa", "code": "ZA", "short_name": "ZAF", "numeric_code": 710},
            {"name": "South Sudan", "code": "SS", "short_name": "SSD", "numeric_code": 728},
            {"name": "Spain", "code": "ES", "short_name": "ESP", "numeric_code": 724},
            {"name": "Sri Lanka", "code": "LK", "short_name": "LKA", "numeric_code": 144},
            {"name": "Sudan", "code": "SD", "short_name": "SDN", "numeric_code": 729},
            {"name": "Suriname", "code": "SR", "short_name": "SUR", "numeric_code": 740},
            {"name": "Sweden", "code": "SE", "short_name": "SWE", "numeric_code": 752},
            {"name": "Switzerland", "code": "CH", "short_name": "CHE", "numeric_code": 756},
            {"name": "Syria", "code": "SY", "short_name": "SYR", "numeric_code": 760},
            {"name": "Taiwan", "code": "TW", "short_name": "TWN", "numeric_code": 158},
            {"name": "Tajikistan", "code": "TJ", "short_name": "TJK", "numeric_code": 762},
            {"name": "Tanzania", "code": "TZ", "short_name": "TZA", "numeric_code": 834},
            {"name": "Thailand", "code": "TH", "short_name": "THA", "numeric_code": 764},
            {"name": "Timor-Leste", "code": "TL", "short_name": "TLS", "numeric_code": 626},
            {"name": "Togo", "code": "TG", "short_name": "TGO", "numeric_code": 768},
            {"name": "Tonga", "code": "TO", "short_name": "TON", "numeric_code": 776},
            {"name": "Trinidad and Tobago", "code": "TT", "short_name": "TTO", "numeric_code": 780},
            {"name": "Tunisia", "code": "TN", "short_name": "TUN", "numeric_code": 788},
            {"name": "Turkey", "code": "TR", "short_name": "TUR", "numeric_code": 792},
            {"name": "Turkmenistan", "code": "TM", "short_name": "TKM", "numeric_code": 795},
            {"name": "Tuvalu", "code": "TV", "short_name": "TUV", "numeric_code": 798},
            {"name": "Uganda", "code": "UG", "short_name": "UGA", "numeric_code": 800},
            {"name": "Ukraine", "code": "UA", "short_name": "UKR", "numeric_code": 804},
            {"name": "United Arab Emirates", "code": "AE", "short_name": "ARE", "numeric_code": 784},
            {"name": "United Kingdom", "code": "GB", "short_name": "GBR", "numeric_code": 826},
            {"name": "United States", "code": "US", "short_name": "USA", "numeric_code": 840},
            {"name": "Uruguay", "code": "UY", "short_name": "URY", "numeric_code": 858},
            {"name": "Uzbekistan", "code": "UZ", "short_name": "UZB", "numeric_code": 860},
            {"name": "Vanuatu", "code": "VU", "short_name": "VUT", "numeric_code": 548},
            {"name": "Vatican City", "code": "VA", "short_name": "VAT", "numeric_code": 336},
            {"name": "Venezuela", "code": "VE", "short_name": "VEN", "numeric_code": 862},
            {"name": "Vietnam", "code": "VN", "short_name": "VNM", "numeric_code": 704},
            {"name": "Yemen", "code": "YE", "short_name": "YEM", "numeric_code": 887},
            {"name": "Zambia", "code": "ZM", "short_name": "ZMB", "numeric_code": 894},
            {"name": "Zimbabwe", "code": "ZW", "short_name": "ZWE", "numeric_code": 716}
        ]

        for country_data in countries:
            country = Country(
                name=country_data["name"],
                iso_alpha2=country_data["code"],
                iso_alpha3=country_data["short_name"],
                iso_numeric=country_data["numeric_code"]
            )
            session.add(country)

        logger.info("✓ Countries added (195 countries)")