"""
SaleFlex.PyPOS - Point of Sale Application
Copyright (C) 2025-2026 Mousavi.Tech

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

# Forms #6 (CLOSURE), #10 (CLOSURE_DETAIL), #11 (CLOSURE_RECEIPTS),
#         #12 (CLOSURE_RECEIPT_DETAIL)
# Provides form-row definitions and all associated UI controls.

from data_layer.enums import FormName, ControlName, EventName
from data_layer.model.definition.form_control import FormControl


def get_form_data(cashier_id: str) -> list[dict]:
    """Return form-row definitions for all closure-related forms (#6, #10, #11, #12)."""
    return [
        {
            'form_no': 6,
            'name': FormName.CLOSURE.name,
            'function': FormName.CLOSURE.name,
            'need_login': True,
            'need_auth': True,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Closure',
            'back_color': '0x2F4F4F',
            'fore_color': '0xFFFFFF',
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
        {
            'form_no': 10,
            'name': FormName.CLOSURE_DETAIL.name,
            'function': FormName.CLOSURE_DETAIL.name,
            'need_login': True,
            'need_auth': True,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Closure Detail',
            'back_color': '0x2F4F4F',
            'fore_color': '0xFFFFFF',
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
        {
            'form_no': 11,
            'name': FormName.CLOSURE_RECEIPTS.name,
            'function': FormName.CLOSURE_RECEIPTS.name,
            'need_login': True,
            'need_auth': True,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Closure Receipts',
            'back_color': '0x2F4F4F',
            'fore_color': '0xFFFFFF',
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
        {
            'form_no': 12,
            'name': FormName.CLOSURE_RECEIPT_DETAIL.name,
            'function': FormName.CLOSURE_RECEIPT_DETAIL.name,
            'need_login': True,
            'need_auth': True,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Receipt Detail',
            'back_color': '0x2F4F4F',
            'fore_color': '0xFFFFFF',
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
    ]


def get_closure_form_controls(closure_form, cashier_id: str) -> list:
    """Return FormControl instances for the CLOSURE form (#6)."""
    return [
        # DataGrid showing previous closures (selectable for DETAIL / RECEIPTS)
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=400,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Closure History",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Select a closure to view details or its receipts",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # Execute closure button
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE.value,
            form_control_function1=EventName.CLOSURE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=480,
            start_position=None,
            caption1="CLOSURE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Execute closure operation",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF0000",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # DETAIL button – open closure detail for selected row
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name="CLOSURE_DETAIL",
            form_control_function1=EventName.CLOSURE_DETAIL_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=200,
            height=99,
            location_x=62,
            location_y=630,
            start_position=None,
            caption1="DETAIL",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="View details of the selected closure",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x2E8B57",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # RECEIPTS button
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name="CLOSURE_RECEIPTS",
            form_control_function1=EventName.CLOSURE_RECEIPTS_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=200,
            height=99,
            location_x=280,
            location_y=630,
            start_position=None,
            caption1="RECEIPTS",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="View receipts of the selected closure",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4169E1",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # BACK button
        FormControl(
            fk_form_id=closure_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Main Menu",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]


def get_closure_detail_form_controls(closure_detail_form, cashier_id: str) -> list:
    """Return FormControl instances for CLOSURE_DETAIL (#10). Returns [] if form is None."""
    if not closure_detail_form:
        return []
    return [
        FormControl(
            fk_form_id=closure_detail_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE_DETAIL_GRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=560,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Closure Details",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Detailed summary of the selected closure",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=closure_detail_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Closure List",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]


def get_closure_receipts_form_controls(closure_receipts_form, cashier_id: str) -> list:
    """Return FormControl instances for CLOSURE_RECEIPTS (#11). Returns [] if form is None."""
    if not closure_receipts_form:
        return []
    return [
        FormControl(
            fk_form_id=closure_receipts_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE_RECEIPTS_DATAGRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=480,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Closure Receipts",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Select a receipt to view its details",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=closure_receipts_form.id,
            fk_parent_id=None,
            name="RECEIPT_DETAIL",
            form_control_function1=EventName.CLOSURE_RECEIPT_DETAIL_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=200,
            height=99,
            location_x=62,
            location_y=630,
            start_position=None,
            caption1="DETAIL",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="View details of the selected receipt",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x2E8B57",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=closure_receipts_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Closure List",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]


def get_closure_receipt_detail_form_controls(closure_receipt_detail_form, cashier_id: str) -> list:
    """Return FormControl instances for CLOSURE_RECEIPT_DETAIL (#12). Returns [] if form is None."""
    if not closure_receipt_detail_form:
        return []
    return [
        # Upper grid – receipt header info
        FormControl(
            fk_form_id=closure_receipt_detail_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE_RECEIPT_DETAIL_GRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=250,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Receipt Info",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="LEFT",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="General information about the selected receipt",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # Lower grid – sold items / line products
        FormControl(
            fk_form_id=closure_receipt_detail_form.id,
            fk_parent_id=None,
            name=ControlName.CLOSURE_RECEIPT_ITEMS_GRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=295,
            location_x=62,
            location_y=318,
            start_position=None,
            caption1="Items",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Products / items sold in this receipt",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xF8F8FF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # BACK button
        FormControl(
            fk_form_id=closure_receipt_detail_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Back to Receipts List",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]
