"""
SaleFlex.PyPOS - Point of Sale Application

Copyright (c) 2025-2026 Ferhat Mousavi

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

# Form #2 — MAIN_MENU
# Provides both the form-row definition and its UI controls.
# Layout (1024x768): 7 navigation buttons centred at x=312 w=400, spacing=90px

from data_layer.enums import FormName, ControlName, EventName
from data_layer.model.definition.form_control import FormControl


def get_form_data(cashier_id: str) -> list[dict]:
    """Return form-row definitions for the MAIN_MENU form (form_no=2)."""
    return [
        {
            'form_no': 2,
            'name': FormName.MAIN_MENU.name,
            'function': FormName.MAIN_MENU.name,
            'need_login': True,
            'need_auth': False,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Main Menu',
            'back_color': '0x2F4F4F',  # DarkSlateGray
            'fore_color': '0xFFFFFF',  # White
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': True,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
    ]


def get_form_controls(main_menu_form, cashier_id: str) -> list:
    """Return FormControl instances for the MAIN_MENU form.

    Layout (1024x768):
      Row 1 SALES       y=70   h=80
      Row 2 CLOSURE     y=160  h=80
      Row 3 SETTINGS    y=250  h=80
      Row 4 CASHIER     y=340  h=80
      Row 5 PRODUCTS(half) + WAREHOUSE(half)  y=430  h=75
      Row 6 CUSTOMER (full width)  y=515  h=75
      LOGOUT bottom-right corner  y=630  h=99
    """
    return [
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_SALE",
            form_control_function1=EventName.SALES_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=70,
            start_position=None,
            caption1="SALES",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Sales Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x228B22",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CLOSURE",
            form_control_function1=EventName.CLOSURE_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=160,
            start_position=None,
            caption1="CLOSURE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Closure Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xDC143C",  # Crimson
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CONFIG",
            form_control_function1=EventName.SETTING_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=250,
            start_position=None,
            caption1="SETTINGS",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Settings Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CASHIER",
            form_control_function1=EventName.CASHIER_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=80,
            location_x=312,
            location_y=340,
            start_position=None,
            caption1="CASHIER MANAGEMENT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Cashier Management Form",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF8C00",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_PRODUCTS",
            form_control_function1=EventName.PRODUCT_LIST_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=195,
            height=75,
            location_x=312,
            location_y=430,
            start_position=None,
            caption1="PRODUCTS",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Go to Product List",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x8B0000",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_WAREHOUSE",
            form_control_function1=EventName.STOCK_INQUIRY.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=195,
            height=75,
            location_x=517,
            location_y=430,
            start_position=None,
            caption1="WAREHOUSE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Open Warehouse / Inventory Management",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x1A5276",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name="GOTO_CUSTOMER",
            form_control_function1=EventName.CUSTOMER_LIST_FORM.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=400,
            height=75,
            location_x=312,
            location_y=515,
            start_position=None,
            caption1="CUSTOMER",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Open Customer Management",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=16,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x7D3C98",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=main_menu_form.id,
            fk_parent_id=None,
            name=ControlName.LOGOUT.value,
            form_control_function1=EventName.LOGOUT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="LOGOUT",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Exit current user session",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]
