"""
SaleFlex.PyPOS - Point of Sale Application
Copyright (C) 2025-2026 Mousavi.Tech

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

# Forms #5 (SALE) and #7 (SUSPENDED_SALES_MARKET)
# Provides form-row definitions and all associated UI controls.

from data_layer.enums import FormName, ControlName, EventName
from data_layer.model.definition.form_control import FormControl


def get_form_data(cashier_id: str) -> list[dict]:
    """Return form-row definitions for SALE (#5) and SUSPENDED_SALES_MARKET (#7)."""
    return [
        {
            'form_no': 5,
            'name': FormName.SALE.name,
            'function': FormName.SALE.name,
            'need_login': True,
            'need_auth': False,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Point of Sale',
            'back_color': '0x2F4F4F',  # DarkSlateGray
            'fore_color': '0xFFFFFF',  # White
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
        {
            'form_no': 7,
            'name': FormName.SUSPENDED_SALES_MARKET.name,
            'function': FormName.SUSPENDED_SALES_MARKET.name,
            'need_login': True,
            'need_auth': False,
            'width': 1024,
            'height': 768,
            'form_border_style': 'SINGLE',
            'start_position': 'CENTERSCREEN',
            'caption': 'SaleFlex - Suspended Sales (Market)',
            'back_color': '0x2F4F4F',
            'fore_color': '0xFFFFFF',
            'show_status_bar': True,
            'show_in_taskbar': False,
            'use_virtual_keyboard': False,
            'is_visible': True,
            'is_startup': False,
            'display_mode': 'MAIN',
            'fk_cashier_create_id': cashier_id,
        },
    ]


def get_sale_form_controls(sale_form, cashier_id: str) -> list:
    """Return all FormControl instances for the SALE form (#5).

    Includes: sales list, numpad, payment list, department buttons,
    PLU buttons, product barcode shortcut buttons, and cash payment buttons.
    """
    sale_controls = [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="SALESLIST",
            form_control_function1=EventName.SALE_OPTION.value,
            form_control_function2=None,
            type_no=4,
            type="SALESLIST",
            width=769,
            height=250,
            location_x=252,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="NUMPAD",
            form_control_function1=EventName.SALE_PLU_BARCODE.value,
            form_control_function2=None,
            type_no=5,
            type="NUMPAD",
            width=242,
            height=338,
            location_x=779,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENTLIST",
            form_control_function1="PAYMENTLIST",
            form_control_function2=None,
            type_no=6,
            type="PAYMENTLIST",
            width=230,
            height=246,
            location_x=547,
            location_y=404,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # PLU inquiry — price + per-warehouse stock lookup, no sale
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PLU_INQUIRY",
            form_control_function1=EventName.PLU_INQUIRY.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=114,
            height=90,
            location_x=547,
            location_y=652,
            start_position=None,
            caption1="PLU",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=18,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x5CB85C",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # X — quantity multiplier; commits numpad value as quantity for next sale
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="QTY_MULTIPLIER",
            form_control_function1=EventName.INPUT_QUANTITY.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=114,
            height=90,
            location_x=663,
            location_y=652,
            start_position=None,
            caption1="X",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=20,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFD700",  # Gold
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="AMOUNTSTABLE",
            form_control_function1="AMOUNTSTABLE",
            form_control_function2=None,
            type_no=7,
            type="AMOUNTSTABLE",
            width=250,
            height=213,
            location_x=1,
            location_y=1,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=0,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=None,
            fore_color=None,
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="BACK",
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=113,
            location_x=1,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xD3D3D3",  # Light Gray
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]

    # Department shortcut buttons (left column)
    # Captions match the DepartmentMainGroup names seeded in department_group.py.
    department_data = [
        ("DEPARTMENT1", "FOOD",       1, 215, 100),
        ("DEPARTMENT2", "TOBACCO",    1, 316, 100),
        ("DEPARTMENT3", "INDIVIDUAL", 1, 417,  99),
    ]
    for name, caption, x, y, h in department_data:
        sale_controls.append(FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name=name,
            form_control_function1=EventName.SALE_DEPARTMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=h,
            location_x=x,
            location_y=y,
            start_position=None,
            caption1=caption,
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=10,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xADD8E6",  # Light Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ))

    # PLU code shortcut buttons (second column from left).
    # keyboard_value is the product code; None lets the runtime resolve by button name.
    # PLU2 → "13" (Warburtons Sliced White Bread), PLU3 → "14" (Lurpak Butter Spreadable).
    plu_data = [
        ("PLU1", 126, 215, 100, None),  # product code "1"  – Baguette
        ("PLU2", 126, 316, 100, "13"),  # product code "13" – Warburtons Sliced White Bread
        ("PLU3", 126, 417,  99, "14"),  # product code "14" – Lurpak Butter Spreadable
    ]
    for name, x, y, h, kbd_val in plu_data:
        sale_controls.append(FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name=name,
            form_control_function1=EventName.SALE_PLU_CODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=h,
            location_x=x,
            location_y=y,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFE4B5",  # Moccasin
            fore_color="0x000000",
            keyboard_value=kbd_val,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ))

    # Product barcode shortcut buttons (grid of 12 buttons – two rightmost replaced by discount buttons)
    product_barcode_buttons = [
        ("PLU5000157070008", 252, 252),
        ("PLU7622210449283", 362, 252),
        ("PLU5000328721575", 472, 252),
        ("PLU8711200334532", 582, 252),
        ("PLU5449000000996", 692, 252),
        ("PLU0746817004304", 802, 252),
        ("PLU5000328355037", 252, 327),
        ("PLU5000157077916", 362, 327),
        ("PLU5010044003089", 472, 327),   # product 13 – Warburtons Sliced White Bread
        ("PLU5740900802725", 582, 327),   # product 14 – Lurpak Butter Spreadable
        ("PLU8001090390021", 692, 327),
        ("PLU8714100852703", 802, 327),
    ]
    for plu_name, x, y in product_barcode_buttons:
        height = 75 if y == 252 else 76
        sale_controls.append(FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name=plu_name,
            form_control_function1=EventName.SALE_PLU_BARCODE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=109,
            height=height,
            location_x=x,
            location_y=y,
            start_position=None,
            caption1="",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFB6C1",  # Light Pink
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ))

    # Discount shortcut buttons — replace the former Milk Chocolate (% discount) and
    # Orange Juice (amount discount) PLU barcode buttons in the top-right corner.
    discount_buttons = [
        # (name, caption1, caption2, fn1, fn2, bg_color, y, height, tooltip)
        (
            "DISCOUNT_PERCENT_BTN",
            "DISC\n%",
            "MARK\n%",
            EventName.DISCOUNT_BY_PERCENT.value,
            EventName.MARKUP_BY_PERCENT.value,
            "0x7B1FA2",   # deep purple
            252,
            75,
            "Percentage discount on last line (state 1). Alternate: percentage markup 1–100 % (state 2). Press FUNC to show alternate labels on all dual buttons; after any dual-button action all return to state 1.",
        ),
        (
            "DISCOUNT_AMOUNT_BTN",
            "DISC\nAMT",
            "MARK\nAMT",
            EventName.DISCOUNT_BY_AMOUNT.value,
            EventName.MARKUP_BY_AMOUNT.value,
            "0xD84315",   # deep orange
            327,
            76,
            "Fixed discount on last line (state 1). Alternate: add markup up to line total (state 2). Press FUNC for alternate labels; after any dual-button action all dual buttons reset to state 1.",
        ),
    ]
    for btn_name, cap1, cap2, fn1, fn2, bg, y, height, tip in discount_buttons:
        sale_controls.append(FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name=btn_name,
            form_control_function1=fn1,
            form_control_function2=fn2,
            type_no=1,
            type="BUTTON",
            width=109,
            height=height,
            location_x=912,
            location_y=y,
            start_position=None,
            caption1=cap1,
            caption2=cap2,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=tip,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color=bg,
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ))

    sale_controls.append(
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="COUPON",
            form_control_function1=EventName.APPLY_COUPON.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=109,
            height=76,
            location_x=912,
            location_y=404,
            start_position=None,
            caption1="COUPON",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Enter or scan a coupon / promotion code (requires_coupon campaigns). Numpad text is used as initial input when present.",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF9800",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        )
    )

    # Cash payment buttons (right of PAYMENTLIST)
    sale_controls += [
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH2000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=83,
            location_x=251,
            location_y=404,
            start_position=None,
            caption1="20 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH5000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=83,
            location_x=251,
            location_y=487,
            start_position=None,
            caption1="50 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CASH10000",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=82,
            location_x=251,
            location_y=570,
            start_position=None,
            caption1="100 £",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="CHANGE",
            form_control_function1=EventName.CHANGE_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=144,
            height=90,
            location_x=251,
            location_y=652,
            start_position=None,
            caption1="CHANGE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Calculate and record change amount",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x87CEEB",  # Sky Blue
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CASH",
            form_control_function1=EventName.CASH_PAYMENT.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=150,
            height=137,
            location_x=396,
            location_y=404,
            start_position=None,
            caption1="CASH",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip=None,
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x90EE90",  # Light Green
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # Dual-function: CREDIT CARD (normal) / PAYMENT screen (FUNC-mode → EventName.PAYMENT)
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_CREDIT",
            form_control_function1=EventName.CREDIT_PAYMENT.value,
            form_control_function2=EventName.PAYMENT.value,
            type_no=1,
            type="BUTTON",
            width=150,
            height=111,
            location_x=396,
            location_y=541,
            start_position=None,
            caption1="CREDIT CARD",
            caption2="PAYMENT",
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Credit card payment. Press FUNC for PAYMENT to open the full payment screen; any dual action resets all dual buttons.",
            image=None,
            image_selected=None,
            font_auto_height=True,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xDDA0DD",  # Plum
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # Dual-function: SUSPEND (normal) / CANCEL (FUNC-mode)
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="PAYMENT_SUSPEND",
            form_control_function1=EventName.SUSPEND_SALE.value,
            form_control_function2=EventName.CANCEL_DOCUMENT.value,
            type_no=1,
            type="BUTTON",
            width=150,
            height=90,
            location_x=396,
            location_y=652,
            start_position=None,
            caption1="SUSPEND",
            caption2="CANCEL",
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Suspend current sale. Press FUNC for CANCEL label (then tap to cancel document); any dual action resets all dual buttons.",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF8C00",  # DarkOrange
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # FUNC — switches captions on all dual-function buttons between state 1 and 2 (no event)
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="FUNC",
            form_control_function1=None,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=113,
            location_x=126,
            location_y=630,
            start_position=None,
            caption1="FUNC",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Toggle dual-function button labels between primary and alternate (same FUNC again restores)",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",  # Steel Blue
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        # Dual-function: SUB TOTAL (normal) / CUSTOMER (FUNC-mode)
        FormControl(
            fk_form_id=sale_form.id,
            fk_parent_id=None,
            name="SUBTOTAL",
            form_control_function1=EventName.SUBTOTAL.value,
            form_control_function2=EventName.CUSTOMER_LIST_FORM.value,
            type_no=1,
            type="BUTTON",
            width=250,
            height=113,
            location_x=1,
            location_y=517,
            start_position=None,
            caption1="SUB TOTAL",
            caption2="CUSTOMER",
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Calculate subtotal. Press FUNC for CUSTOMER label to open customer list; any dual action resets all dual buttons.",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=12,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x2F4F4F",  # Dark Slate Gray
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]

    return sale_controls


def get_suspended_sales_form_controls(suspended_form, cashier_id: str) -> list:
    """Return FormControl instances for the SUSPENDED_SALES_MARKET form (#7)."""
    return [
        FormControl(
            fk_form_id=suspended_form.id,
            fk_parent_id=None,
            name=ControlName.SUSPENDED_SALES_DATAGRID.value,
            form_control_function1=EventName.NONE.value,
            form_control_function2=None,
            type_no=9,
            type="DATAGRID",
            width=900,
            height=520,
            location_x=62,
            location_y=50,
            start_position=None,
            caption1="Suspended receipts",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="NORMAL",
            font="Tahoma",
            icon=None,
            tool_tip="Pending suspended sale documents",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFFFFFF",
            fore_color="0x000000",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=suspended_form.id,
            fk_parent_id=None,
            name="ACTIVATE_SUSPENDED",
            form_control_function1=EventName.RESUME_SALE.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=200,
            height=99,
            location_x=62,
            location_y=630,
            start_position=None,
            caption1="ACTIVATE",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Resume selected suspended sale on the register",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x228B22",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
        FormControl(
            fk_form_id=suspended_form.id,
            fk_parent_id=None,
            name=ControlName.BACK.value,
            form_control_function1=EventName.BACK.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=125,
            height=99,
            location_x=880,
            location_y=630,
            start_position=None,
            caption1="BACK",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Return to previous screen",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=14,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0x4682B4",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cashier_id,
            fk_cashier_update_id=cashier_id,
        ),
    ]


def ensure_sale_form_coupon_button(session) -> None:
    """
    Idempotent: add SALE form COUPON button for databases created before APPLY_COUPON.
    """
    from data_layer.model.definition.cashier import Cashier
    from data_layer.model.definition.form import Form
    from data_layer.model.definition.form_control import FormControl

    sale = session.query(Form).filter(Form.name == FormName.SALE.name).first()
    if not sale:
        return
    exists = (
        session.query(FormControl)
        .filter(
            FormControl.fk_form_id == sale.id,
            FormControl.name == "COUPON",
            FormControl.is_deleted.is_(False),
        )
        .first()
    )
    if exists:
        return
    admin = session.query(Cashier).filter(Cashier.user_name == "admin").first()
    if not admin:
        admin = session.query(Cashier).first()
    cid = admin.id if admin else None
    if not cid:
        return
    session.add(
        FormControl(
            fk_form_id=sale.id,
            fk_parent_id=None,
            name="COUPON",
            form_control_function1=EventName.APPLY_COUPON.value,
            form_control_function2=None,
            type_no=1,
            type="BUTTON",
            width=109,
            height=76,
            location_x=912,
            location_y=404,
            start_position=None,
            caption1="COUPON",
            caption2=None,
            list_values=None,
            dock=None,
            alignment=None,
            text_alignment="CENTER",
            character_casing="UPPER",
            font="Tahoma",
            icon=None,
            tool_tip="Enter or scan a coupon / promotion code (requires_coupon campaigns).",
            image=None,
            image_selected=None,
            font_auto_height=False,
            font_size=11,
            input_type="ALPHANUMERIC",
            text_image_relation=None,
            back_color="0xFF9800",
            fore_color="0xFFFFFF",
            keyboard_value=None,
            fk_cashier_create_id=cid,
            fk_cashier_update_id=cid,
        )
    )
    session.commit()
